global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
- job_name: 'dummyservice-scrape'
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets: ['dummyservice:8080']
    labels:
      application: dummyservice

rule_files:
- "/etc/prometheus/alerts.yml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"